### ISSUE TITLE
Codegen can't generate code at designated path

### ISSUE THREAD

**Issue by kopkunka55** [aws-amplify/amplify-codegen#51] opened 2020-11-11 09:04 UTC
**Describe the bug**
I've tried to generate graphql code like below

```bash
? Choose the code generation language target typescript
? Enter the file name pattern of graphql queries, mutations and subscriptions ./graphql/**/*.ts
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
? Enter the file name for the generated code ./graphql/API.ts
? Do you want to generate code for your newly created GraphQL API Yes
✔ Generated GraphQL operations successfully and saved at src/graphql
```
it's expected to generate the code at `/graphql/*/ts` but the actual graphql code are generated at `src/graphql/*.ts`
Is it possible to generate the code other than /src?

**Amplify CLI Version**
4.26.1

**To Reproduce**
`amplify codegen models` with a path which doesn't include `/src`

**Expected behavior**
graphql code will be generated at `/graphql/*./ts` instead of `/src/graphql/*.ts`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Node Version v12.16.1

**Comment by phani-srikar** [comment] 2021-02-10 03:16
Hi @kopkunka55. Thanks a lot for creating this issue. I am able to reproduce this behavior. We are investigating it and plan to fix this soon.

**Comment by AaronZyLee** [comment] 2021-02-17 19:51
The issue is solved by this PR https://github.com/aws-amplify/amplify-cli/pull/6530. I close the issue for now.

**Closed by AaronZyLee** 2021-02-17 19:51 UTC
Labels: amplify-codegen, bug
