### ISSUE TITLE
added custom lambda resolver using @function directive, codegen fails

### ISSUE THREAD

**Issue by tomhirschfeld** [aws-amplify/amplify-codegen#95] opened 2021-02-25 06:03 UTC
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
i created a custom lambda resolver in my schema.graphql, tested it, it works in my env in the appsync console as expected. When I run "amplify codegen" the following error happens:

```
 $amplify codegen
 
✔ Generated GraphQL operations successfully and saved at src/graphql
Syntax Error: Expected Name, found ( (6:7)
  4 |   )
  5 | {
> 6 |       (
    |       ^
  7 |       reportingGroupId:$reportingGroupId
  8 |   )
  9 |
  ```
  
  and here is the relevant schema:
  
  ```
  type Query {
    getBudgetStatus(reportingGroupId: String): ReportingGroupBudgetStatus @function(name: "getReportingGroupBudgetStatus-${env}")
}

type ReportingGroupBudgetStatus {
    budgetStatusSplit: [BudgetStatusComponent]
}

input RequestUserCampaignCreationInput {
    id: ID
    campaignId: ID!
    userId: ID!
    productId: ID
    campaignApplication: AWSJSON
}
  ```
  
  amplify api gql-compile completes successfully

```
amplify api gql-compile

GraphQL schema compiled successfully.

```

  

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

4.44.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**
codegen executes correctly without error
**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Mac/Windows/Ubuntu]
- Node Version. You can use `node -v` to check the node version on your system

**Log output**
Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Additional context**

**Comment by tomhirschfeld** [comment] 2021-02-26 04:49
still fails

**Comment by AaronZyLee** [comment] 2021-03-02 21:17
@tomhirschfeld I am still not able to reproduce the issue based on your description. The schema(after building) I use is as following.
```GraphQL
type Query {
  getBudgetStatus(reportingGroupId: String): ReportingGroupBudgetStatus
}

type ReportingGroupBudgetStatus {
  budgetStatusSplit: [String]
}
```
However the error indicates that the generated `src/graphql-single/queries.js` has a problem with the missing name field. Could you double check the generated file? If that is the error, you can fix it by adding the missing code manually. 
```JavaScript
/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const getBudgetStatus = /* GraphQL */ `
  query GetBudgetStatus($reportingGroupId: String) {
    /* -------  The error occurs in the line below. In your case `getBudgetStatus` is not generated  --------*/
    getBudgetStatus(reportingGroupId: $reportingGroupId) { 
      budgetStatusSplit
    }
  }
`;
```

**Comment by AaronZyLee** [comment] 2021-03-11 21:36
Make sure you are using the latest CLI and have correct [FF value](https://github.com/aws-amplify/amplify-codegen/blob/master/FeatureFlags.md). Or this is not solved you can refer to the solution from the comment above. I close this issue for now but feel free to reopen if not resolved.

**Closed by AaronZyLee** 2021-03-11 21:36 UTC
Labels: bug, doc-gen, pending-response
