### ISSUE TITLE
[Bug] Schema without "id" field should not validate

### ISSUE THREAD

**Issue by richardmcclellan** [aws-amplify/amplify-codegen#91] opened 2021-02-24 17:29 UTC
### Problem

Recently, a customer in Discord reported getting an `Field 'id' is undefined` error when trying to create an object using Amplify Android.  This is because their @model type did not contain an `id` field, and the Amplify libraries assume that all models do have an `id` field.   

Here is the schema:
```
type SimRecord @model @key(fields: ["simNumber", "user", "simExpiryDate"]) {
   simNumber: String!
   user: String!
   reloadAmount: String!
   reloadPeriod: String!
   simExpiryDate: String!
   reloadsLeft: String
   eror: String
   imei: String
   usuario: String
   vehiculo: String 
}
```

Here is the error

```
GraphQLResponse{data='null', errors='[GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field 'id' in type 'SimRecord' is undefined @ 'createSimRecord/id'', locations='[GraphQLLocation{line='4', column='5'}]', path='null', extensions='null'}]'}
```

### Solution

Codegen should fail to validate any @model types that do not contain an `id: ID!` field.

**Comment by AaronZyLee** [comment] 2021-02-24 18:19
@richardmcclellan I cannot reproduce this issue in model-gen. I check the code and find that model-gen will always ensure ID field in the output. Which codegen do you refer to? Is it related to the type-gen from appsync sdk?

**Comment by richardmcclellan** [comment] 2021-02-24 20:22
hey @AaronZyLee perhaps this is a CLI bug then?   The issue is that, for the schema above, the AppSync operations generated by the CLI DO NOT contain an "id" field, but the code generated models DO contain an "id" field.  So, I guess there are two possible solutions:
1. Update codegen to fail if an "id" is not included on the a @model type in the schema, instead of implicitly adding one.  This was my original suggestion.
2. Update the CLI to implicitly add an "id" field, if not included on the schema.

Let me know which solution you think would be better.

**Comment by AaronZyLee** [comment] 2021-02-24 21:37
@richardmcclellan I double check the customer's schema. According to the [doc](https://docs.amplify.aws/cli/graphql-transformer/key#definition) for `@key`, if you use it without a `name` parameter, it will change the primary key of DynamoDB. Hence the use case of customer falls into using a customized PK as `simNumber` instead of `id`. I am not sure if current Datastore allows for such scenario. AFAIK this is not supported yet in a previous github discussion #42 . If Datastore is incapable of this, we should propose it in the datastore roadmap to solve it.

On the other hand, if the customer compromises that he would like to use `simNumber` as a secondary index, the only change to his schema is to add a `name` field in `@key` as following.
```GraphQL
type SimRecord @model @key(name: "bySimNumber", fields: ["simNumber", "user", "simExpiryDate"]) {
   simNumber: String!
   user: String!
   reloadAmount: String!
   reloadPeriod: String!
   simExpiryDate: String!
   reloadsLeft: String
   eror: String
   imei: String
   usuario: String
   vehiculo: String 
}
```
And in this case since `simNumber` is a secondary index, the default PK `id` will be generated in CLI.
```GraphQL
type SimRecord {
  id: ID!
  simNumber: String!
  user: String!
  reloadAmount: String!
  reloadPeriod: String!
  simExpiryDate: String!
  reloadsLeft: String
  eror: String
  imei: String
  usuario: String
  vehiculo: String
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

type Query {
  getSimRecord(id: ID!): SimRecord
  listSimRecords(filter: ModelSimRecordFilterInput, limit: Int, nextToken: String): ModelSimRecordConnection
}

input CreateSimRecordInput {
  id: ID
  simNumber: String!
  user: String!
  reloadAmount: String!
  reloadPeriod: String!
  simExpiryDate: String!
  reloadsLeft: String
  eror: String
  imei: String
  usuario: String
  vehiculo: String
}
```

**Comment by phani-srikar** [comment] 2021-03-19 17:15
> 1. Update model-gen so that schema validation fails if an "id" is not included on the a @model type in the schema, instead of implicitly adding one.  This was my original suggestion.
> 2. Update the CLI to implicitly add an "id" field, if not included on the schema, just like model-gen does, but for the generated AppSync operations.

We should at-least have proposal 1 in place until the Datastore's necessity for having an `ID` field is mitigated. This issue is possibly a duplicate of https://github.com/aws-amplify/amplify-codegen/issues/42. Closing this in favor of that.

**Closed by phani-srikar** 2021-03-19 17:15 UTC
Labels: bug, pending-response
