### ISSUE TITLE
Amplify codegen for TypeScript generate broken custom queries when have no parameters

### ISSUE THREAD

**Issue by mrmurazza** [aws-amplify/amplify-codegen#733] opened 2023-10-04 01:15 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/main/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.9.0

### Amplify CLI Version

12.5.1

### What operating system are you using?

Mac

### Amplify Codegen Command

codegen

### Describe the bug

I have custom queries & mutations in my `schema.graphql` that does not have parameter.
The snippet of my `schema.graphql` is in other section below.

The generated code in `queries.ts` that I got is:
```
export const getOverview = /* GraphQL */ `query GetOverview {
  getOverview {
    id
    __typename
  }
}
` as GeneratedQuery<
  APITypes.GetOverviewQueryVariables,
  APITypes.GetOverview
>;
```

and in the `graphql.ts` there is no `APITypes.GetOverviewQueryVariables`.
So, it's causing error "... has no exported member name xxx" when I ran `npm run build`

This is my `.graphqlconfig.yml`
```
projects:
  myProject:
    schemaPath: amplify/backend/api/myConnect/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/graphql.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 4
extensions:
  amplify:
    version: 3
```

### Expected behavior

`queries.ts` should not have errors when a custom query don't have parameters.
or in the API.ts should generate APITypes.GetOverviewQueryVariables that could handle queries with no parameters. 

So the generated queries.ts, mutations.ts, & subscriptions.ts could compile on npm run build

### Reproduction steps

1. `amplify upgrade` to 12.5.1
2. have custom queries that have no parameters in schema.graphql
3. run `amplify codegen`
4. run `npm run build`
5. it will cause the build error with " ... has no exported members"

### GraphQL schema(s)

<details>

```graphql
type Query {
  getOverview : ResponseObject
    @function(name: "functionName-${env}")
    @auth(rules: [{ allow: private }])
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by dd-ssc** [comment] 2023-10-04 20:22
Incidentally, I asked pretty much the same question on [stackoverflow.com](https://stackoverflow.com/a/77216199) recently.

**Comment by ErlendHer** [comment] 2023-10-04 22:38
We're having the same issue, could you verify that your API.ts is actually being generated?

In our case, the new codegen actually failed to generate a new API.ts file and it was using an older version which caused this error.

**Comment by mrmurazza** [comment] 2023-10-04 22:58
> We're having the same issue, could you verify that your API.ts is actually being generated?
> 
> In our case, the new codegen actually failed to generate a new API.ts file and it was using an older version which caused this error.

Yes, the API.ts is generated.

I previously had issue with the API.ts not being generated, but now I got it generated by re-doing `amplify codegen configure` as mentioned by someone in the discord channel:
https://discord.com/channels/705853757799399426/1155199104985604126/1155199104985604126

Specifically, by changing the `includes` part in the `.graphqlconfig.yml` to `src/graphql/**/*.ts`, which previously was the default value `src/graphql/**.grapql.ts`

After, API.ts got generated, now my next issue is with queries with no parameters that still ask for *QueryVariables that is not generated in the API.ts

**Comment by ErlendHer** [comment] 2023-10-04 23:01
Thank you. In our case, we were unable to generate the API.ts file unless we made sure the output directory was empty before running the codegen.

We're also having the exact same issue as you btw, all of our custom Mutations / Queries / Subscriptions without input parameters failed after running codegen with the latest CLI version.  +1

**Comment by dpilch** [comment] 2023-10-11 19:43
I was able to reproduce the issue with the following minimum schema. There seems to be an issue with any custom query.

```
type Query {
  getCustomFoo: Foo
}

type Foo @model {
  id: ID!
}
```

Marking as a bug and investigating a fix.

**Comment by dpilch** [comment] 2023-10-11 20:01
Fixed by https://github.com/aws-amplify/amplify-codegen/pull/737. It will be available in a future release.

**Comment by dpilch** [comment] 2023-10-11 20:02
Duplicate of https://github.com/aws-amplify/amplify-codegen/issues/736

**Closed by dpilch** 2023-10-11 20:02 UTC
Labels: bug
