### ISSUE TITLE
Unknown directive "aws_lambda".

### ISSUE THREAD

**Issue by yosdanybm** [aws-amplify/amplify-codegen#241] opened 2021-09-25 04:09 UTC
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

6.0.1

### What operating system are you using?

Windows

### Amplify Codegen Command

codegen

### Describe the bug

Hi, I'm trying to generate the queries, mutations and subscriptions from a schema.graphql that has the recent authorization mode "AWS_LAMBDA" ([more information](https://aws.amazon.com/es/blogs/mobile/appsync-lambda-auth/)), and it throws me the error: 

`Unknown directive "aws_lambda".`

I used the plugin module to execute amplify-codegen@2.26.5

### Expected behavior

The generation of queries, mutations and subscriptions.

### Reproduction steps

1.`amplify codegen`
2.`? Select the plugin module to execute amplify-codegen@2.26.5`
3. Error: `Unknown directive "aws_lambda".`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type ActionResponse @aws_lambda {
  Code: Int
  Message: String
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by jevakallio** [comment] 2021-11-05 09:25
In case it isn't obvious, just adding here that until this issue gets fixed, projects that rely on Amplify's codegen cannot adopt the [AppSync Lambda Auth](https://aws.amazon.com/blogs/mobile/appsync-lambda-auth/) feature.

I tried to contribute a fix to this issue but ran into #283.

**Comment by jeroenmeulendijks** [comment] 2021-12-04 22:24
@jevakallio Do you already have a fix and was #283 blocking you from submitting the fix? If so I see that you closed #283, so would love to see your fix on this issue.

**Comment by AndreasEK** [comment] 2022-03-23 16:47
still present in 7.6.26

not sure what https://github.com/aws-amplify/amplify-cli/issues/9227 addressed, including the fix, but an "amplify codegen" still leads to the above mentioned errors

**Comment by AaronZyLee** [comment] 2022-03-30 18:04
@AndreasEK Thanks for reporting the issue. I am using the same version of CLI but cannot reproduce the issue. The error was thrown by transformer because it did not recognize the directive, which is fixed in the CLI PR you mentioned. Could you confirm if the issue still persists in CLI@v7.6.26? The schema I used for reproducing the issue is as follows FYI
```GraphQL
type ActionResponse @aws_lambda @model {
  Code: Int
  Message: String
}
```

**Comment by AndreasEK** [comment] 2022-03-31 06:39
For me, this is a rather old amplify project, that we migrated from amplify-cli 6.x to the latest version. The issue was still persistent yesterday with the latest version (7.6.26). I found out, however, that changing the feature flag [`usedocsgeneratorplugin`](https://docs.amplify.aws/cli/reference/feature-flags/#useDocsGeneratorPlugin) in `amplify/cli.json` to `true`, the error went away. I could not figure out, what behaviour exactly changed with the docs generator plugin, but at least it is working again. So maybe this is rather a migration issue?

``` json
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": false,
      "cleangeneratedmodelsdirectory": false,
      "retaincasestyle": false,
      "addtimestampfields": false,
      "handlelistnullabilitytransparently": false,
      "emitauthprovider": false,
      "generateindexrules": false,
      "enabledartnullsafety": false
    },
```


P.S. I'm pretty sure I left this comment already yesterday, but maybe I was just typing it, got distracted and forgot to actually submit the comment.

**Comment by AaronZyLee** [comment] 2022-03-31 16:42
Exactly this is a migration issue. Those are feature flags we use for migration purpose and they are to be deprecated in the future. I will put this task in our backlog.

**Closed by AaronZyLee** 2022-03-31 16:42 UTC
Labels: feature-request, doc-gen, type-gen

**Comment by ezalorsara** [comment] 2022-04-28 12:24
Hi is there any update about this I'm using  v8.0.3
![image](https://user-images.githubusercontent.com/6506275/165751317-408be500-3d5b-484e-9c27-fb06ffcd023d.png)

Thanks

**Comment by AndreasEK** [comment] 2022-04-28 13:49
@ezalorsara you need to change a feature flag as outlined in https://github.com/aws-amplify/amplify-codegen/issues/241#issuecomment-1084156495

**Comment by ezalorsara** [comment] 2022-04-28 16:00
> 

Yes I change/copy the example config above, "usedocsgeneratorplugin": true. but still having those issue I'm using amplify v8.0.3.
here is my cli.json
```
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": false,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": false,
      "secondarykeyasgsi": false,
      "skipoverridemutationinputtypes": false,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true,
      "securityenhancementnotification": true,
      "securityEnhancementNotification": false,
      "showfieldauthnotification": false
    },
    "frontend-ios": {
      "enablexcodeintegration": false
    },
    "auth": {
      "enablecaseinsensitivity": false,
      "useinclusiveterminology": false,
      "breakcirculardependency": false,
      "forcealiasattributes": false,
      "useenabledmfas": false
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": false,
      "cleangeneratedmodelsdirectory": false,
      "retaincasestyle": false,
      "addtimestampfields": false,
      "handlelistnullabilitytransparently": false,
      "emitauthprovider": false,
      "generateindexrules": false,
      "enabledartnullsafety": false
    },
    "appsync": {
      "generategraphqlpermissions": false
    },
    "latestregionsupport": {
      "pinpoint": 0,
      "translate": 0,
      "transcribe": 0,
      "rekognition": 0,
      "textract": 0,
      "comprehend": 0
    },
    "project": {
      "overrides": true
    }
  }
}
```
Thank you

**Comment by AndreasEK** [comment] 2022-04-29 06:39
I can only speculate that for you it's than any of the other feature flags in codegen that might help, if you set it to true. :/
