### ISSUE TITLE
Unknown field argument owner when using owner rules in Datastore

### ISSUE THREAD

**Issue by amin79** [aws-amplify/amplify-codegen#117] opened 2020-12-31 21:50 UTC
**Describe the bug**
I'm using expo with amplify datastore. When I assign owner rule to a model, I get some warnings like
```
[WARN] 29:35.271 DataStore - Sync error, Connection failed: {"errors":[{"message":"Validation error of type UnknownArgument: Unknown field argument owner @ 'onDeleteUser'"}]}
```

When I create a record, it would be save locally but not sync with the dynamoDB table in cloud.

If I remove the owner rule and just use "allow: private", the data also be saved in the cloud, but there is no "owner" field in the table which I need it.

**To Reproduce**
Here one of the models:
```graphql
type Setting
  @model
  @auth(
    rules: [
      { allow: owner, identityClaim: "sub", operations: [read, create, update] }
      { allow: private, operations: [read] }
    ]
  ) {
  id: ID!
  currency: String!
  owner: String
}
```
**Expected behavior**
I expected to have synced data in the cloud and also owner field in my table.

**What is Configured?**
I use Cognito for authentication and authorization.
Users login with their Google or Facebook accounts.

**Comment by duranmla** [comment] 2021-10-04 12:45
In my case, I was able to get rid of the warnings by updating the permissions of the model. Because by mistake I was allowing anyone logged in to have edit, update, delete permissions over the model. **Once I update to make sure only owner can edit** I solve the warning.

<img width="280" alt="CleanShot 2021-10-04 at 14 44 20@2x" src="https://user-images.githubusercontent.com/1425162/135853740-087a6227-4cdf-41c4-b287-13d89715d5a1.png">

**Comment by alharris-at** [comment] 2022-04-05 18:34
Hi @amin79, are you encountering this issue?

**Comment by alharris-at** [comment] 2022-04-21 18:34
Closing as not reproducible right now. We have significantly refactored the auth codegen and transformer logic with GraphQL v2, which has likely addressed the issues here.

**Closed by alharris-at** 2022-04-21 18:34 UTC
Labels: bug, model-gen
