### ISSUE TITLE
Graphql schema limitations for using amplify codegen

### ISSUE THREAD

**Issue by alushnikov-aurea** [aws-amplify/amplify-codegen#27] opened 2020-09-30 17:33 UTC
**Which Category is your question related to?**
Amplify Codegen

**Amplify CLI Version** 
4.29.3

**What AWS Services are you utilizing?**
AppSync

**Provide additional details e.g. code snippets**

I have GraphQL schema which is deployed to AWS AppSync, and trying to use amplify codegen to generate static types for it.
Experimentally it was found out that codegen fails if:
1. Types implementing the same interface have properties of different type. F.e. something like this
```
interface Object {
  id: String
}
type Child1 implements Object {
  id: String
  location: Location
}
type Child2 implements Object {
  id: String
  location: String
}
```
Will produce `Fields "location" conflict because they return conflicting types String and Location. Use different aliases on the fields to fetch both if this was intentional.`

2. Subqueries for types with required arguments also throw errors. F.e.:
```
type Child2 implements Object {
  id: String
  location(city: String!): String
}
```
Will produce `Field "location" argument "city" of type "String!" is required, but it was not provided.`

So I was wondering if there are some limitations/rules which amplify codegen imposes on graphql schema, or there's some configuration that can be used to resolve these problems.

**Comment by rzinnatullin** [comment] 2021-03-08 13:49
Here's the data to reproduce: https://drive.google.com/drive/folders/1wAPAIm1W1ws12SyjQVDe3Z6IrcykNi9n?usp=sharing
And here's the repro video: https://drive.google.com/file/d/1BphJphcHM4C1qqiKQUjdqYuFh_tRfs8j/view?usp=sharing

The GraphQL schema is simple:
```graphql
type Document implements Object {
	id: ID
	index: Int
}

interface Object {
	id: ID
}

type Place implements Object {
	id: ID
	index: String
}

type Query {
	obj: Object
}

schema {
	query: Query
}
```

**Comment by rzinnatullin** [comment] 2021-03-09 05:13
So, looks like the problem is in the generated query. This is the generated `queries.ts` contents:
```typescript
export const obj = /* GraphQL */ `
  query Obj {
    obj {
      id
      ... on Document {
        index
      }
      ... on Place {
        index
      }
    }
  }
`;
```
As you can see, the query contains `index` field for both types (`Document` and `Place`), and this query is indeed invalid because `index` has different types.

In theory, it's possible to adapt the existing GraphQL API to workaround this issue, but in practice, it's not the way to go.

Any ideas? Is it a known Amplify limitation?

**Comment by AaronZyLee** [comment] 2021-03-22 21:28
@rzinnatullin It is not the limitation for amplify codegen but the graphql-js. The error is thrown by the schema validation of `graphql`. I also notice a similar [github issue](https://github.com/dotansimha/graphql-code-generator/issues/2781). I suggest to use the alias as the following instead if you have two different types of the same field name. The `queries.ts` generated by doc-gen just serves as a starting point. The naming for alias is much flexible and it is better to change the query manually to use your own alias names.
```
export const obj = /* GraphQL */ `
  query Obj {
    obj {
      id
      ... on Document {
        docIdx: index
      }
      ... on Place {
        placeIdx: index
      }
    }
  }
`;
```

**Comment by rzinnatullin** [comment] 2021-03-23 09:48
@AaronZyLee Thanks. There's no problem with `graphql-js`, it does its work perfectly fine. The problem is with the codegen itself - it generates an invalid query. My expectation from the codegen is that it just gives me a valid output.

**Comment by AaronZyLee** [comment] 2021-03-23 14:22
@rzinnatullin I agree. The doc-gen is much like a starting point and cannot handle some customized situations. The solution to this is to add the alias names where there is a conflict and since the alias names are much random and customized we recommend to modify the queries manually as I mentioned in the last comment. I will close this issue but feel free to reopen it if the problem is not resolved.

**Closed by AaronZyLee** 2021-03-23 14:22 UTC
Labels: type-gen

**Comment by rzinnatullin** [comment] 2021-03-24 05:48
Hi @AaronZyLee 
well, for a production schema it logs about 5000 errors:
![image](https://user-images.githubusercontent.com/11244866/112261098-fc3b8000-8c8c-11eb-95f8-1eb34ab184f9.png)

So the solution you suggested doesn't look to be usable in this case.
I'm not sure why are you saying that it's a customized situation.

I believe that the codegen generation approach should be redesigned.
Also, why it's not allowing just TypeScript types generation w/o the queries generation? There should not be any problem with generating types for schema.
![image](https://user-images.githubusercontent.com/11244866/112261723-335e6100-8c8e-11eb-94a8-ad1267650e67.png)

**Comment by PatrykMilewski** [comment] 2023-09-15 12:56
We are facing exactly the same issues, as @rzinnatullin said, solution proposed by @AaronZyLee doesn't make sense at all.

Can this issue be reopened since the issue still exists in the latest version? IMO it should either automatically add those aliases or be able to skip directly to just types generation
